In [1]:
import numpy as np
import networkx as nx
from utils import *
from generator import ER_generator, draw_anomalies
import community
import scipy
from scipy import sparse
from scipy.stats import norm
import logging
logging.basicConfig(format='%(name)s - %(levelname)s - %(message)s', level=logging.INFO)

In [2]:
obs_network = ER_generator(n=1000)
obs_network = draw_anomalies(obs_network)

Adding 12 anomalies...
The 1th anomaly...
0
Adding trees...
9
The 2th anomaly...
9
17
Adding cliques...
The 3th anomaly...
17
24
Adding rings...
The 4th anomaly...
24
36
Adding paths...
[511 520 861 642 629 795 697 357 286 958 187  89]
The 5th anomaly...
36
49
Adding cliques...
The 6th anomaly...
49
68
Adding paths...
[920 105 696 279 624 689 432 169 656 899 134 525 926 686 104 591 593 180
   8]
The 7th anomaly...
68
86
Adding cliques...
The 8th anomaly...
86
96
Adding paths...
[346 998 561 662 936 110 359 804 765 907]
The 9th anomaly...
96
108
Adding stars...
The 10th anomaly...
108
122
Adding paths...
[289  21 834 278 704 811 407 337 355 901  60 419 362 862]
The 11th anomaly...
122
139
Adding rings...
The 12th anomaly...
139
153
Adding rings...


In [3]:
null_models = generate_null_model(num_models=10, n=1000)

root - INFO - Generating 1-th null model
root - INFO - Partitioning graph
root - INFO - Generating 2-th null model
root - INFO - Partitioning graph
root - INFO - Generating 3-th null model
root - INFO - Partitioning graph
root - INFO - Generating 4-th null model
root - INFO - Partitioning graph
root - INFO - Generating 5-th null model
root - INFO - Partitioning graph
root - INFO - Generating 6-th null model
root - INFO - Partitioning graph
root - INFO - Generating 7-th null model
root - INFO - Partitioning graph
root - INFO - Generating 8-th null model
root - INFO - Partitioning graph
root - INFO - Generating 9-th null model
root - INFO - Partitioning graph
root - INFO - Generating 10-th null model
root - INFO - Partitioning graph


In [4]:
null_vectors = [comm_eigenvectors(comm) for comm in null_models]

/opt/miniconda3/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:296: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
/opt/miniconda3/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:203: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  'is in the CSC matrix format', SparseEfficiencyWarning)
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Usin

In [5]:
len(null_vectors), len(null_vectors[0]), null_vectors[0][0].shape, null_vectors[1][0].shape

(10, 4, (49, 20), (55, 20))

In [6]:
obs_comms = partition_graph(obs_network)
obs_comms = [obs_network.subgraph(comm) for comm in obs_comms]

In [7]:
obs_comm_vectors = [comm_eigenvectors(comm) for comm in obs_comms if nx.number_of_nodes(comm)>4]

root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vectors
root - INFO - Using sparse method to compute eigen vecto

In [19]:
from spectral_localisation import *

In [9]:
obs_upper = obs_comm_vectors[0][0]

In [10]:
null_upper = [null_vs[0] for null_vs in null_vectors]

In [11]:
iprs, exps = norm_based_scores(obs_upper, null_upper)

In [12]:
ipr90_scores, abs90_scores = direct_score(obs_upper, null_upper)

In [15]:
ipr90_scores

array([0.32501377, 0.29628557, 0.39134275, 0.28408147, 0.26891444,
       0.30256788, 0.39703666, 0.36799631, 0.39859374, 0.38039837,
       0.39137682, 0.3742271 , 0.39538413, 0.39617513, 0.39891813,
       0.33497379, 0.28424849, 0.39847299, 0.38696402, 0.35906758])

In [16]:
sign_stat_1, sign_stat_2, sign_stat_equal_1, sign_stat_equal_2 = sign_based_score(obs_upper, null_upper)

In [18]:
total_scores = spectral_localization_features(obs_c)

(41, 20)